### PR TITLE
Ensure stable topology ops

### LINKED ISSUE #83: dune-cornerpoint can't load the Norne grid
Before #81 this was hidden by the fact that EclipseGridParser could not load the deck:

```
and@heuristix:~/src/ewoms|master > cat tutorial/tutorial1.cc
#include "config.h"
#include <dune/grid/CpGrid.hpp>
#include <opm/parser/eclipse/Parser/Parser.hpp>
#include <opm/parser/eclipse/Deck/Deck.hpp>
#include <dune/common/mpihelper.hh>

int main(int argc, char **argv)
{
    Dune::MPIHelper::instance(argc, argv);
    Opm::ParserPtr parser(new Opm::Parser);
    Opm::DeckConstPtr deck(parser->parseFile(argv[1]));

    Dune::CpGrid grid;
    grid.processEclipseFormat(deck, /*zTolerance=*/0, /*isPeriodic=*/false);

    return 0;
}
and@heuristix:~/src/ewoms|master > ./bin/tutorial1 /home/and/Norne/Norne_ATW_2013/NORNE_ATW2013.DATA
tutorial1: /home/and/src/dune-cornerpoint/dune/grid/cpgrid/readEclipseFormat.cpp:631: void Dune::<anonymous namespace>::buildTopo(const processed_grid &, std::vector<int> &, cpgrid::OrientedEntityTable<0, 1> &, cpgrid::OrientedEntityTable<1, 0> &, Opm::SparseTable<int> &, std::vector<array<int, 8> > &, std::vector<int> &): Assertion `f2c == f2c_again' failed.
[heuristix:26953] *** Process received signal ***
[heuristix:26953] Signal: Aborted (6)
[heuristix:26953] Signal code:  (-6)
[heuristix:26953] [ 0] /lib64/libc.so.6(+0x358d0) [0x7f2d04b2a8d0]
[heuristix:26953] [ 1] /lib64/libc.so.6(gsignal+0x39) [0x7f2d04b2a849]
[heuristix:26953] [ 2] /lib64/libc.so.6(abort+0x148) [0x7f2d04b2bcd8]
[heuristix:26953] [ 3] /lib64/libc.so.6(+0x2e616) [0x7f2d04b23616]
[heuristix:26953] [ 4] /lib64/libc.so.6(+0x2e6c2) [0x7f2d04b236c2]
[heuristix:26953] [ 5] ./bin/tutorial1() [0x4d8045]
[heuristix:26953] [ 6] ./bin/tutorial1(_ZN4Dune6cpgrid10CpGridData20processEclipseFormatERK6grdecldbb+0xf7) [0x4d7477]
[heuristix:26953] [ 7] ./bin/tutorial1(_ZN4Dune6cpgrid10CpGridData20processEclipseFormatESt10shared_ptrIKN3Opm4DeckEEdbbb+0x122f) [0x4d61ff]
[heuristix:26953] [ 8] ./bin/tutorial1(_ZN4Dune6CpGrid20processEclipseFormatESt10shared_ptrIKN3Opm4DeckEEdbbb+0x88) [0x4cca38]
[heuristix:26953] [ 9] ./bin/tutorial1(main+0x174) [0x4c3674]
[heuristix:26953] [10] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f2d04b16be5]
[heuristix:26953] [11] ./bin/tutorial1() [0x4c3425]
[heuristix:26953] *** End of error message ***
Aborted
```

### PR DESCRIPTION
**Pull request by atgeirr**
Sorting faces' cell neighbours by index ensures that the makeInverseRelation() function yields stable results, i.e. inverting twice yields the same table back.

The code without this PR is not wrong, and yields equivalent but not identical topology tables. The cost of the extra sorting is less than 0.1 second on the Norne grid.

This fixes #83.

### CODE REVIEW

**Comment by blattms** [comment]
After merging will the ordering be the same as for UnstructuredGrid?

**Comment by atgeirr** [comment]
> After merging will the ordering be the same as for UnstructuredGrid?

Good point. It depends on what you mean: cell and face orders are unchanged, only the order of the (typically two) cell-neighbours of some of the faces. Since UnstructuredGrid (or to be specific, the create_grid_cornerpoint() function) just grabs the pointer from the output of process_grdecl() that mapping (face->cell) will be different (but equivalent). I am pretty sure that the cell->face mapping becomes identical between the two though.

File: dune/grid/cpgrid/OrientedEntityTable.hpp [hunk 1]
```diff
@@ -162,6 +164,36 @@ namespace Dune
 		return super_t::operator==(other);
 	    }
 
+            /** @brief Prints the relation matrix corresponding to the table, sparse format.
+
+             Let the entities of codimensions f and t be given by
+             the sets \f$E^f = { e^f_i } \f$ and \f$E^t = { e^t_j }\f$.
+             A relation matrix R is defined by
+	     \f{eqnarray*}{
```
Comment (bska) [inline dune/grid/cpgrid/OrientedEntityTable.hpp]: Does Doxygen not support anything more well-behaved than `eqnarray`?

If I were writing this in a regular document I'd use something like
```latex
\usepackage{amsmath}
% ...
\begin{document}
% ...
\[
R_{ij} =
\begin{cases}
  \phantom{-} 0, &\quad \text{if } e_i^f \text{ and } e_j^f \text{ are not neighbours}, \\
  \phantom{-} 1, &\quad \text{if } e_i^f \text{ and } e_j^f \text{ are neighbours with same orientation}, \\
           -  1, &\quad \text{if } e_i^f \text{ and } e_j^f \text{ are neighbours with opposite orientation}.
\end{cases}
\]
```
Is that not possible in Doxygen?

Comment (atgeirr) [inline dune/grid/cpgrid/OrientedEntityTable.hpp]: Probably, but I do not know for sure. The doc in question is partially copied from the pre-existing non-sparse version.

Comment (bska) [inline dune/grid/cpgrid/OrientedEntityTable.hpp]: > Probably, but I do not know for sure

I don't know what the "probably" refers to, so I can't reply intelligently.  However, our [`cmake/Templates/Doxyfile`](https://github.com/OPM/dune-cornerpoint/blob/master/cmake/Templates/Doxyfile#L1147) does include the request
```
# The EXTRA_PACKAGES tag can be to specify one or more names of LaTeX
# packages that should be included in the LaTeX output.

EXTRA_PACKAGES         = amsmath
```
so using the previously suggested `cases` construction should be possible.  Would you mind trying that?

In general `eqnarray` should not be used at all in any documents, but it seems impossible to eliminate due to old habits.

**Comment by atgeirr** [comment]
I have improved docs as requested. @blattms can you tell us if this would negatively affect your work in any way? Otherwise I'd like to have this merged.

**Comment by blattms** [comment]
On Mon, Mar 02, 2015 at 02:07:31AM -0800, @atgeirr wrote:
> I have improved docs as requested. @blattms can you tell us if this would negatively affect your work in any way? Otherwise I'd like to have this merged.

Merging should be fine.

**Comment by bska** [comment]
> Merging should be fine.

While I'd prefer that we didn't introduce any **new** tab-vs-space issues into this file (there are already quite enough), I'll just do a final build test and merge if it goes through.

**Comment by bska** [comment]
Builds and all tests run on GCC 4.4/CentOS 5.11.  I'll merge into master.
